// import $ from 'jquery'
import '../../assets/style/index.scss'
import '../../common'
import '../../includes/mixins/SearchTab'
import '../../includes/mixins/CategoryMenu/index'
import '../../includes/mixins/OpacityBanner/index'
import '../../includes/mixins/Tab'
